### PR TITLE
Support for Kubernetes v1.22

### PR DESCRIPTION
**Pull request by MartinWeindel**
**What this PR does / why we need it**:
Added support for Kubernetes v1.22 as some apiVersions are not available anymore.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
Support for Kubernetes v1.22
```

### CODE REVIEW

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the effort to make this controller 1.22 ready. Looks good to me. Can you also update the `examples/controller-registration.yaml` file?

**Comment by MartinWeindel** [comment]
> Can you also update the `examples/controller-registration.yaml` file?
Done, thanks for the hint.

**Review by timuthy — APPROVED** [review]
/lgtm

**Comment by timuthy** [comment]
Part of gardener/gardener#4363

**Pull request merged**
