### PR TITLE
Added Cloudflare as a DNS provider

### LINKED ISSUE #58: Add Cloudflare as a DNS provider
**What would you like to be added**:
I would like to see Cloudflare as a DNS provider
**Why is this needed**:
Cloudflare is one of the biggest names in the internet and is one of the largest DNS providers. We ourselves are using Cloudflare as our DNS provider and the [cert-manager](https://cert-manager.io/docs/configuration/acme/dns01/cloudflare/) project itself has Cloudflare as a supported provider for ACME deployments.

### PR DESCRIPTION
**Pull request by SayakMukhopadhyay**
**What this PR does / why we need it**:
This adds Cloudflare as a DNS Provider
**Which issue(s) this PR fixes**:
Fixes #58 

**Special notes for your reviewer**:
Unlike other providers, Cloudflare doesn't take multiple values for a record. Their way of doing things is to create separate record for each value so that needs to be taken into account. I have tried to implement a clean way of doing it.
**Release note**:

```improvement operator

```

### CODE REVIEW

**Comment by mandelsoft** [comment]
Hi @SayakMukhopadhyay ,
I just had a look into your pull request. Thank you very much for your contribution.

If I understood the *cloudflare* API correctly (according to your way to use it), every single record (IP address. text record line, etc) has its own Id, that is required to update or delete this dedicated record. Therefore you are using a lookup call for every record to determine its Id when doing deletes or updates.
This has several problems:
- first of all, the number of API calls doubles with the number of modifications.
- in contrast to such APIs like route53, where a complete record set of a dedicated type is updated as a whole, here the delta of the members of a record set must be handled, explicitly. This means for updates of a record set, some members must be deleted, updated or created. This handling seems to be completely missing.

This general API behavior is similar to the already existing implementation for *AliCloud*. So this can be used as a template for the implementation for *cloudflare*. 

I've started to support *infoblox* which follows the same pattern. Therefore I've generalized this pattern and based the *alicloud* and *infoblox* handling on this abstraction. It is not yet merged, but can be found in branch `testupdate`. 

I don't know, how urgent the *cloudflare* support is, but there are three possibilities:
- you could try to base your implementation on the actual *alicloud* solution, and I will later migrate it to the new abstraction.
- I provide a preliminary version for this abstraction on a dedicated branch, you can base your pull request on.
- you can wait until I can merge my changes.

Please tell me what path you want to follow, then I'll try to provide a base version as soon as possible.

I don't know anything about the *cloudflare* environment, so far. But is it possible, to forward zone with this environment (records of type `NS`)? If so, this handling is missing, also.

**Comment by mandelsoft** [comment]
I've reorganized this history of the working tree and provided a branch `base` that has a chance to be merged soon. It already contains the abstraction mentioned above and can be used as base for your pull request.

**Comment by SayakMukhopadhyay** [comment]
> I don't know anything about the _cloudflare_ environment, so far. But is it possible, to forward zones with this environment (records of type `NS`)? If so, this handling is missing, also.

Well, I forgot to add that. I will work on it.

> I don't know, how urgent the _cloudflare_ support is, but there are three possibilities:
> 
>     * you could try to base your implementation on the actual _alicloud_ solution, and I will later migrate it to the new abstraction.
> 
>     * I provide a preliminary version for this abstraction on a dedicated branch, you can base your pull request on.
> 
>     * you can wait until I can merge my changes.

I will be honest, it is moderately urgent, reason why I took up on working on it even though I have never worked on Go. As such, I am willing to do whichever allows us to have cloudflare DNS support at the earliest, preferable before the end of this month (that's when I estimated I could start deploying Gardener locally). In short I am hoping to have cloudflare support on the next release. (Btw, do we know about when the next release in planned?).

**Comment by mandelsoft** [comment]
We already have some fixes in the queue, so we can make a new release whenever the pull request is merged. Do you need some help with the new baseline? Don't hesitate to ask.

**Comment by SayakMukhopadhyay** [comment]
That's great to know. Right now my PR is based on the `upstream/master`. Should I just rebase my master to `upstream/base` branch and over-right the `origin/master`. (I don't know if github can handle PRs when the remote's history is rewritten.)

**Comment by mandelsoft** [comment]
We will not rewrite the master, if you base you pull request it will include everything on top of master, so my changes would be included. Don't bother about this, we will merge the base branch before your PR, and then everything should be fine.

**Comment by SayakMukhopadhyay** [comment]
Ok, then I am rebasing my local `master` to the `upstream/base`. For reference, it looks like this:
image
Let me know if it looks good and I will start with the fixes.

**Comment by mandelsoft** [comment]
Looks fine, are you on Slack? This might be easier.

**Comment by rfranzke** [comment]
Nice PR! 💯

**Pull request merged**
