### PR TITLE
Provider PowerDNS implementation

### PR DESCRIPTION
**Pull request by simcod**
**What this PR does / why we need it**:
Adds PowerDNS as additional provider.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```feature operator
Adds PowerDNS as additional provider
```

### CODE REVIEW

**Comment by gardener-robot-ci-1** [comment]
Thank you @simcod for your contribution. Before I can start building your PR, a member of the organization must set the required label(s) {'reviewed/ok-to-test'}. Once started, you can check the build status in the PR checks section below.

**Comment by MartinWeindel** [comment]
@simcod 
Thanks for your contribution!

As I'm not very familiar with PowerDNS, can you explain, why it is not sufficient to the the provider type `rfc2136` for PowerDNS. According to the [documentation](https://doc.powerdns.com/authoritative/dnsupdate.html) it should support it.
Have you tried it?

**Comment by robertvolkmann** [comment]
Hi @MartinWeindel, we've opted to use the REST interface of PowerDNS to maintain consistency with the code base of our [PowerDNS extension](https://github.com/metal-stack/gardener-extension-dns-powerdns).

**Review by MartinWeindel — CHANGES_REQUESTED** [review]
Thanks for your contribution. Implementation looks good to me.

Please add documentation about credentials secrets and examples.
Similar to:
- https://github.com/gardener/external-dns-management/blob/master/README.md?plain=1#L15
- https://github.com/gardener/external-dns-management/tree/master/docs/rfc2136
- https://github.com/gardener/external-dns-management/blob/master/examples/20-secret-rfc2136-credentials.yaml
- https://github.com/gardener/external-dns-management/blob/master/examples/30-provider-rfc2136.yaml

**Comment by simcod** [comment]
@MartinWeindel Thank you for your feedback. 

I added documentation about credentials and examples.

**Review by MartinWeindel — APPROVED** [review]
/lgtm

Thanks for your contribution!

**Pull request merged**
